#Basic Info
title: J. Danny Mendoza blog
author: J. Danny Mendoza
email: jdmendoza@alumni.scu.edu
description: Knowledge Without Action is Useless,   So I Build Stuff
twitter_username: dmendoza_py
github_username: jdmendoza
linkedin_username: jdmendoza1
disqus:
  shortname: jdmendoza-github-io


#Build Settings
markdown: kramdown
theme: minimal

header_pages:
  - project_directory.md
  - about.md
