#Basic Info
title: Data Science & Machine Learning Blog
author: J. Danny Mendoza
email: jdannym93@gmail.com
description: An Awesome Blog
twitter_username: Jdanny650
github_username: jdmendoza
linkedin_username: jdmendoza1



#Build Settings
markdown: kramdown
theme: minima
