theme: jekyll-theme-minimal
title: [Data Science Repository by Danny Mendoza]
description: [This is my portfolio of data science projects.
Each project has a link to the GitHub repo,
a short project description and any additional relevant documentation]
